ekf_filter_node:
    ros__parameters:
        frequency: 30.0
        # two_d_mode: true
        odom0: /Odometry_fixed
        odom0_config: [
                true, # x
                true, # y
                false, # z
                false, # roll
                false, # pitch
                true, # yaw
                true, # vx
                true, # vy
                false, # vz
                false, # vroll
                false, # vpitch
                true, # vyaw
                false, # ax
                false, # ay
                false, # az
            ]
        base_link_frame: base_footprint
        odom_frame: odom
        world_frame: odom
        publish_tf: true
        use_control: false
